spring:
  application:
    name: MainMicroservice
  datasource:
    username: kirill
    password: password
    url: jdbc:mysql://database-2.c7uga2ee4fql.eu-west-2.rds.amazonaws.com:3306/main_microservice
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true