spring:
  application:
    name: MainMicroservice
  datasource:
    username: kirill
    password: password
    url: jdbc:mysql://localhost:3306/main_microservice
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin